CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(250)                            NOT NULL,
    email VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_user_email_ UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_name UNIQUE (name)
);
CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT4                                  NOT NULL,
    lon FLOAT4                                  NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initiator          BIGINT                                  NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    description        VARCHAR(7000)                           NOT NULL,
    event_date         TIMESTAMP                               NOT NULL,
    creation_on        TIMESTAMP default current_timestamp,
    published_on       TIMESTAMP,
    location_id        BIGINT                                  NOT NULL,
    paid               BOOLEAN   DEFAULT false,
    participant_limit  INTEGER   DEFAULT 0,
    request_moderation BOOLEAN   DEFAULT true,
    title              VARCHAR(120)                            NOT NULL,
    state              VARCHAR(10)                             NOT NULL,
    views              INTEGER   DEFAULT 0,
    confirmed_requests INTEGER   DEFAULT 0,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_category_events FOREIGN KEY (category_id) REFERENCES categories,
    CONSTRAINT fk_location_events FOREIGN KEY (location_id) REFERENCES locations,
    CONSTRAINT fk_initiator_events FOREIGN KEY (initiator) REFERENCES users
);
CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN DEFAULT false,
    title  VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT,
    event_id       BIGINT,
    CONSTRAINT fk_compilation_id FOREIGN KEY (compilation_id) references compilations,
    CONSTRAINT fk_compilation_event FOREIGN KEY (event_id) references events,
    CONSTRAINT uq_compilation_event UNIQUE (compilation_id, event_id)
);
CREATE TABLE IF NOT EXISTS participation
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id  BIGINT                                  NOT NULL,
    requester BIGINT                                  NOT NULL,
    status    VARCHAR(10)                             NOT NULL,
    created   TIMESTAMP DEFAULT current_timestamp,
    CONSTRAINT pk_participation PRIMARY KEY (id),
    CONSTRAINT fk_participation_event FOREIGN KEY (event_id) references events,
    CONSTRAINT fk_participation_requester FOREIGN KEY (requester) references users,
    CONSTRAINT uq_event_requester UNIQUE (event_id, requester)
);