server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/stat
    username: stat
    password: stat
---
logging:
  level:
    ru.practicum: debug
spring:
  config:
    activate:
      on-profile: ci,test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:stat;MODE=PostgreSQL
    username: test
    password: test
  h2:
    console:
      enabled: true

